---
- hosts: martha # AQUÍ ESPECIFICAMOS AL HOST O GRUPO DE HOST 
  remote_user: root # USUARIO QUE OCUPAMOS PARA EJECUTAR LAS TAREA
  tasks:
   - name: Levantar el servicio de Docker 
     service: name=docker state=started # LEVANTAMOS EL DEMONIO DEDOCKER
   - name: Crear un contenedor de apache 
     docker_container: #CREAMOS  UN CONTENEDOR
        name: Apache #NOMBRE DEL CONTENEDOR
        image: httpd #IMAGEN DE LA CUAL APARTIR VAMOS A CREAR EL CONTENEDOR
        volumes: /opt/apache:/var/www/html # VOLUMEN  QUE ESTAMOS MONTANDO DEL HOST AL CONTENEDOR
        ports: 8080:80 # PUERTO DONDE ESTAMOS PUBLICANDO EL SERVICIO
   - name: Mostrar todos los contenedores que se están ejecutándose
     command: docker ps 
     register: docker
   - debug: var=docker.stdout